<?php

/**
 * PluginPlanAttachmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPlanAttachmentTable extends AttachmentTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPlanAttachmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPlanAttachment');
    }
}